# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MyCode\Personal-App\QtPersonalApp\popup_plan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Popup_Plan(object):
    def setupUi(self, Popup_Plan):
        Popup_Plan.setObjectName("Popup_Plan")
        Popup_Plan.resize(466, 173)
        self.popup_add_plan = QtWidgets.QFrame(Popup_Plan)
        self.popup_add_plan.setGeometry(QtCore.QRect(0, 0, 201, 165))
        self.popup_add_plan.setStyleSheet("#popup_add_plan{\n"
"    background-color: #D2E3C8;\n"
"    border-radius: 15;\n"
"    border:1px solid white;\n"
"}")
        self.popup_add_plan.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.popup_add_plan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.popup_add_plan.setObjectName("popup_add_plan")
        self.plainTextEdit_detailPlan = QtWidgets.QPlainTextEdit(self.popup_add_plan)
        self.plainTextEdit_detailPlan.setGeometry(QtCore.QRect(40, 80, 151, 51))
        font = QtGui.QFont()
        font.setFamily("SamsungOne")
        font.setBold(False)
        self.plainTextEdit_detailPlan.setFont(font)
        self.plainTextEdit_detailPlan.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_detailPlan.setPlainText("")
        self.plainTextEdit_detailPlan.setObjectName("plainTextEdit_detailPlan")
        self.label_23 = QtWidgets.QLabel(self.popup_add_plan)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 21, 21))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-note-40.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.pushButton_SetPlan = QtWidgets.QPushButton(self.popup_add_plan)
        self.pushButton_SetPlan.setGeometry(QtCore.QRect(70, 135, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SetPlan.setFont(font)
        self.pushButton_SetPlan.setStyleSheet("#pushButton_SetPlan\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SetPlan::pressed\n"
"{\n"
"    background-color: #B5CB99;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SetPlan::hover\n"
"{\n"
"    background-color: #B5CB99;\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-next-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SetPlan.setIcon(icon)
        self.pushButton_SetPlan.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SetPlan.setObjectName("pushButton_SetPlan")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.popup_add_plan)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(40, 45, 151, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setBold(True)
        self.plainTextEdit_10.setFont(font)
        self.plainTextEdit_10.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_10.setPlainText("")
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.label_25 = QtWidgets.QLabel(self.popup_add_plan)
        self.label_25.setGeometry(QtCore.QRect(8, 45, 28, 28))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.pushButton_Selectday_Plan = QtWidgets.QPushButton(self.popup_add_plan)
        self.pushButton_Selectday_Plan.setGeometry(QtCore.QRect(165, 47, 21, 24))
        self.pushButton_Selectday_Plan.setStyleSheet("#pushButton_Selectday_Plan\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_Selectday_Plan::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_Selectday_Plan::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_Selectday_Plan.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Selectday_Plan.setIcon(icon1)
        self.pushButton_Selectday_Plan.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Selectday_Plan.setObjectName("pushButton_Selectday_Plan")
        self.label_date_selected_Plan = QtWidgets.QLabel(self.popup_add_plan)
        self.label_date_selected_Plan.setGeometry(QtCore.QRect(60, 47, 91, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_date_selected_Plan.setFont(font)
        self.label_date_selected_Plan.setStyleSheet("#label_date_selected_Plan{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid white;\n"
"    color: black\n"
"}")
        self.label_date_selected_Plan.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_selected_Plan.setObjectName("label_date_selected_Plan")
        self.plainTextEdit_Time = QtWidgets.QPlainTextEdit(self.popup_add_plan)
        self.plainTextEdit_Time.setGeometry(QtCore.QRect(60, 10, 97, 28))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.plainTextEdit_Time.setFont(font)
        self.plainTextEdit_Time.setStyleSheet("border-radius: 10;\n"
"background-color: white;\n"
"border: 1px solid gray;\n"
"padding-left: 5")
        self.plainTextEdit_Time.setCenterOnScroll(False)
        self.plainTextEdit_Time.setObjectName("plainTextEdit_Time")
        self.label_26 = QtWidgets.QLabel(self.popup_add_plan)
        self.label_26.setGeometry(QtCore.QRect(11, 15, 21, 21))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-clock-30.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.comboBox_MonthThu = QtWidgets.QComboBox(self.popup_add_plan)
        self.comboBox_MonthThu.setGeometry(QtCore.QRect(105, 11, 51, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.comboBox_MonthThu.setFont(font)
        self.comboBox_MonthThu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_MonthThu.setAutoFillBackground(False)
        self.comboBox_MonthThu.setStyleSheet("#comboBox_MonthThu {\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"    color: black;\n"
"}\n"
"#comboBox_MonthThu::drop-down {\n"
"    width: 10px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"#comboBox_MonthThu::down-arrow {\n"
"    image: url(\":/Icon/Image/time.png\");\n"
"    width: 18;\n"
"    height: 18;\n"
"    padding-right: 20\n"
"}")
        self.comboBox_MonthThu.setEditable(False)
        self.comboBox_MonthThu.setMaxVisibleItems(10)
        self.comboBox_MonthThu.setObjectName("comboBox_MonthThu")
        self.comboBox_MonthThu.addItem("")
        self.comboBox_MonthThu.addItem("")
        self.PopupselectDay_Thu = QtWidgets.QFrame(Popup_Plan)
        self.PopupselectDay_Thu.setGeometry(QtCore.QRect(210, 0, 191, 71))
        self.PopupselectDay_Thu.setStyleSheet("#PopupselectDay_Thu{\n"
"    background-color: white;\n"
"    border-radius: 15;\n"
"    border: 2px solid white;\n"
"}")
        self.PopupselectDay_Thu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PopupselectDay_Thu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PopupselectDay_Thu.setObjectName("PopupselectDay_Thu")
        self.label_21 = QtWidgets.QLabel(self.PopupselectDay_Thu)
        self.label_21.setGeometry(QtCore.QRect(40, 37, 31, 31))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/Icon/Image/icons8-calendar-48.png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.pushButton_SelectedDay_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_SelectedDay_Thu.setGeometry(QtCore.QRect(70, 40, 71, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_SelectedDay_Thu.setFont(font)
        self.pushButton_SelectedDay_Thu.setStyleSheet("#pushButton_SelectedDay_Thu\n"
"{\n"
"    border: 0px solid white;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"#pushButton_SelectedDay_Thu::pressed\n"
"{\n"
"    background-color: #99FFFF;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_SelectedDay_Thu::hover\n"
"{\n"
"    background-color: #BBBBBB;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_SelectedDay_Thu.setIcon(icon)
        self.pushButton_SelectedDay_Thu.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_SelectedDay_Thu.setObjectName("pushButton_SelectedDay_Thu")
        self.pushButton_back_day_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_back_day_Thu.setGeometry(QtCore.QRect(0, 10, 30, 30))
        self.pushButton_back_day_Thu.setStyleSheet("#pushButton_back_day_Thu\n"
"{\n"
"    background-color: white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_back_day_Thu:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_back_day_Thu:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_back_day_Thu.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/Image/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_day_Thu.setIcon(icon2)
        self.pushButton_back_day_Thu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_back_day_Thu.setObjectName("pushButton_back_day_Thu")
        self.pushButton_next_day_Thu = QtWidgets.QPushButton(self.PopupselectDay_Thu)
        self.pushButton_next_day_Thu.setGeometry(QtCore.QRect(160, 10, 30, 30))
        self.pushButton_next_day_Thu.setStyleSheet("#pushButton_next_day_Thu\n"
"{\n"
"    background-color :white ;\n"
"    border-radius: 15;\n"
"}\n"
"#pushButton_next_day_Thu:pressed\n"
"{\n"
"    background-color: white;\n"
"    border-style: inset;\n"
"}\n"
"#pushButton_next_day_Thu:hover\n"
"{\n"
"    background-color: #CCFFFF;\n"
"    border-style: inset;\n"
"}")
        self.pushButton_next_day_Thu.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/Image/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_day_Thu.setIcon(icon3)
        self.pushButton_next_day_Thu.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_next_day_Thu.setObjectName("pushButton_next_day_Thu")
        self.label_date_select_Thu = QtWidgets.QLabel(self.PopupselectDay_Thu)
        self.label_date_select_Thu.setGeometry(QtCore.QRect(30, 10, 131, 25))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.label_date_select_Thu.setFont(font)
        self.label_date_select_Thu.setStyleSheet("#label_date_select_Thu{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"    border: 1px solid gray;\n"
"    color: black\n"
"}")
        self.label_date_select_Thu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_select_Thu.setObjectName("label_date_select_Thu")

        self.retranslateUi(Popup_Plan)
        self.comboBox_MonthThu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Popup_Plan)

    def retranslateUi(self, Popup_Plan):
        _translate = QtCore.QCoreApplication.translate
        Popup_Plan.setWindowTitle(_translate("Popup_Plan", "Dialog"))
        self.pushButton_SetPlan.setText(_translate("Popup_Plan", "Enter"))
        self.label_date_selected_Plan.setText(_translate("Popup_Plan", "09/12/2023"))
        self.plainTextEdit_Time.setPlainText(_translate("Popup_Plan", "09:09"))
        self.comboBox_MonthThu.setItemText(0, _translate("Popup_Plan", "AM"))
        self.comboBox_MonthThu.setItemText(1, _translate("Popup_Plan", "PM"))
        self.pushButton_SelectedDay_Thu.setText(_translate("Popup_Plan", "Enter"))
        self.label_date_select_Thu.setText(_translate("Popup_Plan", "09/12/2023"))
import ResourceFile_rc
